services:

# Kafka without zookeeper

#   kafka:
#     image: bashj79/kafka-kraft
#     container_name: kafka
#     ports:
#       - "9092:9092"

  # kafka-ui-kpow:
  #   image: factorhouse/kpow-ce:latest
  #   container_name: kafka-ui-kpow
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     BOOTSTRAP: "kafka:9092"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G

# Kafka with zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "3000:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092  
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
